// Library dispatched action types.
export const WEBSOCKET_BEGIN_RECONNECT = 'REDUX_WEBSOCKET::BEGIN_RECONNECT';
export const WEBSOCKET_RECONNECT_ATTEMPT = 'REDUX_WEBSOCKET::RECONNECT_ATTEMPT';
export const WEBSOCKET_RECONNECTED = 'REDUX_WEBSOCKET::RECONNECTED';
export const WEBSOCKET_BROKEN = 'REDUX_WEBSOCKET::BROKEN';
export const WEBSOCKET_CLOSED = 'REDUX_WEBSOCKET::CLOSED';
export const WEBSOCKET_ERROR = 'REDUX_WEBSOCKET::ERROR';
export const WEBSOCKET_MESSAGE = 'REDUX_WEBSOCKET::MESSAGE';
export const WEBSOCKET_OPEN = 'REDUX_WEBSOCKET::OPEN';

// User dispatched action types.
export const WEBSOCKET_CONNECT = 'REDUX_WEBSOCKET::CONNECT';
export const WEBSOCKET_DISCONNECT = 'REDUX_WEBSOCKET::DISCONNECT';
export const WEBSOCKET_SEND = 'REDUX_WEBSOCKET::SEND';
